#version 450
#include "precision.glsl"
#include "common.glsl"
layout(local_size_x = 256) in;
layout(std430, binding = 0) readonly  buffer S { STORE s[]; };
layout(std430, binding = 1) writeonly buffer D { STORE d[]; };
layout(push_constant) uniform PC { uint count; int op; float a, b; } pc;
void main() {
  uint i = gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * gl_NumWorkGroups.x * gl_WorkGroupSize.x;
  if (i >= pc.count) return;
  d[i] = STORE(vx_unary(float(s[i]), pc.op, pc.a, pc.b));
}
