#!/usr/bin/env python3
"""Embed compiled SPIR-V (.spv) blobs into a single C++ translation unit.

Usage: embed_spirv.py <out.cpp> <a.spv> <b.spv> ...
Generates vx::embeddedShaders() -> map<name, vector<uint32_t>>.
"""
import sys, os, struct

def main():
    out = sys.argv[1]
    spvs = sys.argv[2:]
    lines = [
        "// AUTO-GENERATED by tools/embed_spirv.py — do not edit.",
        "#include <cstdint>", "#include <map>", "#include <string>", "#include <vector>",
        "namespace vknn {",
    ]
    names = []
    for spv in spvs:
        name = os.path.splitext(os.path.basename(spv))[0]
        with open(spv, "rb") as f:
            data = f.read()
        assert len(data) % 4 == 0, f"{spv} not 4-byte aligned"
        words = struct.unpack(f"<{len(data)//4}I", data)
        sym = "g_spv_" + name.replace("-", "_")
        names.append((name, sym, len(words)))
        body = ",".join(str(w) for w in words)
        lines.append(f"static const uint32_t {sym}[] = {{{body}}};")
    lines.append("const std::map<std::string,std::vector<uint32_t>>& embeddedShaders() {")
    lines.append("  static const std::map<std::string,std::vector<uint32_t>> m = {")
    for name, sym, n in names:
        lines.append(f'    {{"{name}", std::vector<uint32_t>({sym}, {sym}+{n})}},')
    lines.append("  };")
    lines.append("  return m;")
    lines.append("}")
    lines.append("}  // namespace vknn")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"embed_spirv: wrote {len(names)} shaders -> {out}")

if __name__ == "__main__":
    main()
