#!/usr/bin/env python3
"""Embed compiled SPIR-V (.spv) blobs into a single C++ translation unit.

Usage: embed_spirv.py <out.cpp> <a.spv> <b.spv> ...
Generates:
  vknn::embeddedShaders()      -> map<name, vector<uint32_t>>
  vknn::embeddedShadersHash()  -> md5 hex of all kernels (the cache's kernel-version guard). Any shader
                                  change alters the SPIR-V and thus the hash, invalidating stale caches.
"""
import sys, os, struct, hashlib

def main():
    out = sys.argv[1]
    spvs = sys.argv[2:]
    # Read every blob and sort by name so the hash is independent of the argument order.
    shaders = []
    for spv in spvs:
        name = os.path.splitext(os.path.basename(spv))[0]
        with open(spv, "rb") as f:
            data = f.read()
        assert len(data) % 4 == 0, f"{spv} not 4-byte aligned"
        shaders.append((name, data))
    shaders.sort(key=lambda x: x[0])

    h = hashlib.md5()
    for name, data in shaders:
        h.update(name.encode("utf-8"))
        h.update(data)
    kernel_hash = h.hexdigest()

    lines = [
        "// AUTO-GENERATED by tools/embed_spirv.py — do not edit.",
        "#include <cstdint>", "#include <map>", "#include <string>", "#include <vector>",
        "namespace vknn {",
    ]
    names = []
    for name, data in shaders:
        words = struct.unpack(f"<{len(data)//4}I", data)
        sym = "g_spv_" + name.replace("-", "_")
        names.append((name, sym, len(words)))
        body = ",".join(str(w) for w in words)
        lines.append(f"static const uint32_t {sym}[] = {{{body}}};")
    lines.append("const std::map<std::string,std::vector<uint32_t>>& embeddedShaders() {")
    lines.append("  static const std::map<std::string,std::vector<uint32_t>> m = {")
    for name, sym, n in names:
        lines.append(f'    {{"{name}", std::vector<uint32_t>({sym}, {sym}+{n})}},')
    lines.append("  };")
    lines.append("  return m;")
    lines.append("}")
    lines.append(f'const char* embeddedShadersHash() {{ return "{kernel_hash}"; }}')
    lines.append("}  // namespace vknn")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"embed_spirv: wrote {len(names)} shaders (kernelHash={kernel_hash}) -> {out}")

if __name__ == "__main__":
    main()
